### ISSUE TITLE
Potential bug "pi is None"

### ISSUE THREAD

**Issue by tcal-x** [tdene/synth_opt_adders#98]
```
            for pi in range(len(pins)):
                net = pins[pi]
                if pi is None:
                    continue
```

Should this be `if net is None:` ?

https://github.com/tdene/synth_opt_adders/blob/main/src/pptrees/ExpressionNode.py#L375

**Comment by tdene** [comment]
`pn` is an awful name. I need to global-replace that variable name with `pin_name`.

But yes! I had to walk through the logic to make sure, but yeah, that was a typo. Thanks for the catch!

Luckily, that faulty if statement would only get triggered if two nodes get partially (but not fully) disconnected, which is not something currently possible (nor do I think it ever will be, but might as well account for it).

Thanks, fixed, will push the patch through today and getting some more fixes in.
